name: "CI"

on:
  workflow_dispatch:
    inputs:
      Docker:
        required: false
        default: false
        type: boolean
      Release:
        required: false
        default: false
        type: boolean

# TODO Comment out the next 2 lines so that it won't interfere with the old CI when tagging a version
#      Should fix after deprecate the old CI(build.yml)
#   push:
#     tags: ["v*.*.*"]

env:
  SCCACHE_GHA_ENABLED: true
  RUSTC_WRAPPER: sccache
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  multiarch:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write
      packages: write
    needs: [linux]
    if: github.event_name == 'push' || inputs.Docker
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: musl
          - target: gnu
    steps:
      - name: Extract Metadata for Docker
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ${{github.repository}}
            ghcr.io/${{github.repository}}
          flavor: |
            suffix=${{ endsWith(matrix.target, 'musl') && '-alpine' || '' }},onlatest=true
          tags: |
            type=ref,event=tag
            type=edge,branch=multiarch
            type=semver,pattern=v{{major}}.{{minor}}

      - name: Log In to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{github.token}}

      - name: Log In to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{github.repository_owner}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Create Manifest List
        run: |
          IFS='\n' read -r tags <<< "${{ steps.meta.outputs.tags }}"
          for tag in $tags; do
            docker manifest create $tag \
            --amend $tag-amd64 \
            --amend $tag-arm64
            docker manifest push $tag
          done

  linux:
    permissions:
      id-token: write
      contents: write
      attestations: write
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
          - target: x86_64-unknown-linux-musl
          - target: aarch64-unknown-linux-gnu
            build_env: "JEMALLOC_SYS_WITH_LG_PAGE=16"
          - target: aarch64-unknown-linux-musl
            build_env: "JEMALLOC_SYS_WITH_LG_PAGE=16"
          - target: armv7-unknown-linux-gnueabihf
            build_env: "JEMALLOC_SYS_WITH_LG_PAGE=16"
          - target: armv7-unknown-linux-musleabihf
            build_env: "JEMALLOC_SYS_WITH_LG_PAGE=16"
          - target: arm-unknown-linux-gnueabihf
          - target: arm-unknown-linux-musleabihf

    name: Build / ${{matrix.target}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log In to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{github.token}}

      - name: Log In to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{github.repository_owner}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Cache apt
        uses: actions/cache@v4
        id: apt-cache
        with:
          path: |
            var-cache-apt
            var-lib-apt
          key: docker-apt-cache-${{ hashFiles('Dockerfile.build') }}

      - name: Calculate shasum of external deps
        id: cal-dep-shasum
        run: |
          echo "checksum=$(yq -p toml -oy '.package[] | select((.source | contains("")) or (.checksum | contains("")))' Cargo.lock | sha256sum | awk '{print $1}')" >> "$GITHUB_OUTPUT"

      - name: Get latest zig version
        id: zig-version
        run: |
          echo "zig_version=$(curl -s "https://api.github.com/repos/ziglang/zig/releases/latest" | jq -r '.tag_name')" >> "$GITHUB_OUTPUT"

      - name: Cache Cargo
        uses: actions/cache@v4
        id: cargo-cache
        with:
          path: |
            usr-local-cargo-registry
            usr-local-cargo-git
          key: docker-cargo-cache-${{ steps.cal-dep-shasum.outputs.checksum }}

      - name: Inject cache into docker
        uses: reproducible-containers/buildkit-cache-dance@v3.1.2
        with:
          cache-map: |
            {
              "var-cache-apt": "/var/cache/apt",
              "var-lib-apt": "/var/lib/apt",
              "usr-local-cargo-registry": "/usr/local/cargo/registry",
              "usr-local-cargo-git": "/usr/local/cargo/git"
            }
          skip-extraction: ${{ steps.cargo-cache.outputs.cache-hit }} && ${{ steps.apt-cache.outputs.cache-hit }}

      - name: Extract Metadata for Docker
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ${{github.repository}}
            ghcr.io/${{github.repository}}
          flavor: |
            suffix=${{ endsWith(matrix.target, 'musl') && '-alpine' || '' }}${{ startsWith(matrix.target, 'x86') && '-amd64' || '-arm64' }},onlatest=true
          tags: |
            type=ref,event=tag
            type=edge,branch=multiarch
            type=semver,pattern=v{{major}}.{{minor}}

      - name: Build Artifact
        id: build
        uses: docker/bake-action@v6
        env:
          TARGET: ${{matrix.target}}
          DOCKER_BUILD_RECORD_UPLOAD: false
          ARTIFACT_REPO: ghcr.io/${{github.repository}}
          BUILD_ENV: ${{matrix.build_env}}
          ZIG_VERSION: ${{ steps.zig-version.outputs.zig_version }}
          DOCKER_PLATFORM: ${{ startsWith(matrix.target, 'x86') && 'amd64' || 'arm64' }}
        with:
          source: .
          files: |
            docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          targets: ${{(github.event_name == 'push' || inputs.Docker) && (startsWith(matrix.target, 'x86') || startsWith(matrix.target, 'aarch64')) && 'build,image' || 'build'}}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.target}}
          path: |
            artifact
            !artifact/*.json

      - name: Get image digest
        id: image-digest
        if: (github.event_name == 'push' || inputs.Docker) && (startsWith(matrix.target, 'x86') || startsWith(matrix.target, 'aarch64'))
        run: |
          echo "image_digest=$(echo '${{ steps.build.outputs.metadata }}' | jq -r '.image.["containerimage.digest"]')" >> "$GITHUB_OUTPUT"

      - name: Attest Dockerhub
        uses: actions/attest-build-provenance@v2
        if: (github.event_name == 'push' || inputs.Docker) && (startsWith(matrix.target, 'x86') || startsWith(matrix.target, 'aarch64'))
        with:
          subject-name: index.docker.io/${{github.repository}}
          subject-digest: ${{ steps.image-digest.outputs.image_digest }}
          push-to-registry: true

      - name: Attest GHCR
        uses: actions/attest-build-provenance@v2
        if: (github.event_name == 'push' || inputs.Docker) && (startsWith(matrix.target, 'x86') || startsWith(matrix.target, 'aarch64'))
        with:
          subject-name: ghcr.io/${{github.repository}}
          subject-digest: ${{ steps.image-digest.outputs.image_digest }}
          push-to-registry: true

  windows:
    name: Build / ${{matrix.target}}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        #   - target: aarch64-pc-windows-msvc
          - target: x86_64-pc-windows-msvc

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.7
        with:
          disable_annotations: true

      - name: Build
        run: |
          rustup target add ${{matrix.target}}
          cargo build --release --target "${{matrix.target}}" -p mail-server -p stalwart-cli
          mkdir -p artifacts
          mv ./target/${{matrix.target}}/release/stalwart-mail.exe ./artifacts/stalwart-mail.exe
          mv ./target/${{matrix.target}}/release/stalwart-cli.exe ./artifacts/stalwart-cli.exe

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.target}}
          path: artifacts

  macos:
    name: Build / ${{matrix.target}}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-apple-darwin
          - target: x86_64-apple-darwin
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.7
        with:
          disable_annotations: true

      - name: Build FoundationDB Edition
        run: |
          rustup target add ${{matrix.target}}
          # Get latest FoundationDB installer
          curl -Lo foundationdb.pkg "https://glare.now.sh/apple/foundationdb/${{startsWith(matrix.target, 'x86') && 'x86_64' || 'arm64'}}.pkg"
          sudo installer -allowUntrusted -dumplog -pkg foundationdb.pkg -target /
          cargo build --release --target "${{matrix.target}}" -p mail-server --no-default-features --features "foundationdb elastic s3 redis enterprise"
          mkdir -p artifacts
          mv ./target/${{matrix.target}}/release/stalwart-mail ./artifacts/stalwart-mail-foundationdb

      - name: Build
        run: |
          rustup target add ${{matrix.target}}
          cargo build --release --target "${{matrix.target}}" -p mail-server -p stalwart-cli
          mkdir -p artifacts
          mv ./target/${{matrix.target}}/release/stalwart-mail ./artifacts/stalwart-mail
          mv ./target/${{matrix.target}}/release/stalwart-cli ./artifacts/stalwart-cli

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.target}}
          path: artifacts

  release:
    name: Release
    permissions:
      id-token: write
      contents: write
      attestations: write
    if: github.event_name == 'push' || inputs.Release
    needs: [linux, windows, macos]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: archive

      - name: Compress
        run: |
          set -eux
          BASE_DIR="$(pwd)/archive"
          compress_files() {
              local dir="$1"
              cd "$dir"
              # Process each file in the directory
              for file in `ls`; do
                  filename="${file%.*}"
                  extension="${file##*.}"
                  if [ "$extension" = "exe" ]; then
                      7z a -tzip "${filename}-${dir}.zip" "$file" > /dev/null
                  else
                      tar -czf "${filename}-${dir}.tar.gz" "$file"
                  fi
              done
              cd $BASE_DIR
          }
          cd $BASE_DIR
          for arch_dir in `ls`; do
              dir_name=$(basename "$arch_dir")
              compress_files "$dir_name"
          done

      - name: Attest binary
        id: attest
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: |
            archive/**/*.tar.gz
            archive/**/*.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            archive/**/*.tar.gz
            archive/**/*.zip
          prerelease: ${{!startsWith(github.ref, 'refs/tags/') || null}}
          tag_name: ${{!startsWith(github.ref, 'refs/tags/') && 'nightly' || null}}
          append_body: true
          body: |
            <hr />

            ## Check binary attestation at [here](${{ steps.attest.outputs.attestation-url }})
